// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3uNlBHd4aE9t-CPwml9GzB72ZZRYP4gA',
    appId: '1:1021312431585:web:ed12c5372b7f7c15710ea0',
    messagingSenderId: '1021312431585',
    projectId: 'e-commerce-app-3f294',
    authDomain: 'e-commerce-app-3f294.firebaseapp.com',
    storageBucket: 'e-commerce-app-3f294.firebasestorage.app',
    measurementId: 'G-HL825KYLMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0tSb1XYVotwAjECrdqhQw80wpiDGAPGk',
    appId: '1:1021312431585:android:87eb11e8d0098787710ea0',
    messagingSenderId: '1021312431585',
    projectId: 'e-commerce-app-3f294',
    storageBucket: 'e-commerce-app-3f294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjA15WVKxEPm4Z0bzglFWK7sPYj8E2xbs',
    appId: '1:1021312431585:ios:51b1ef455cdd1311710ea0',
    messagingSenderId: '1021312431585',
    projectId: 'e-commerce-app-3f294',
    storageBucket: 'e-commerce-app-3f294.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjA15WVKxEPm4Z0bzglFWK7sPYj8E2xbs',
    appId: '1:1021312431585:ios:51b1ef455cdd1311710ea0',
    messagingSenderId: '1021312431585',
    projectId: 'e-commerce-app-3f294',
    storageBucket: 'e-commerce-app-3f294.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3uNlBHd4aE9t-CPwml9GzB72ZZRYP4gA',
    appId: '1:1021312431585:web:ffb11a70c599bffa710ea0',
    messagingSenderId: '1021312431585',
    projectId: 'e-commerce-app-3f294',
    authDomain: 'e-commerce-app-3f294.firebaseapp.com',
    storageBucket: 'e-commerce-app-3f294.firebasestorage.app',
    measurementId: 'G-NW0T96N89R',
  );

}